# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.22

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Disable VCS-based implicit rules.
% : %,v

# Disable VCS-based implicit rules.
% : RCS/%

# Disable VCS-based implicit rules.
% : RCS/%,v

# Disable VCS-based implicit rules.
% : SCCS/s.%

# Disable VCS-based implicit rules.
% : s.%

.SUFFIXES: .hpux_make_needs_suffix_list

# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/giovany/Development/GioEngine

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/giovany/Development/GioEngine/build

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "No interactive CMake dialog available..."
	/usr/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# Special rule for the target list_install_components
list_install_components:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Available install components are: \"Unspecified\""
.PHONY : list_install_components

# Special rule for the target list_install_components
list_install_components/fast: list_install_components
.PHONY : list_install_components/fast

# Special rule for the target install
install: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Install the project..."
	/usr/bin/cmake -P cmake_install.cmake
.PHONY : install

# Special rule for the target install
install/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Install the project..."
	/usr/bin/cmake -P cmake_install.cmake
.PHONY : install/fast

# Special rule for the target install/local
install/local: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing only the local directory..."
	/usr/bin/cmake -DCMAKE_INSTALL_LOCAL_ONLY=1 -P cmake_install.cmake
.PHONY : install/local

# Special rule for the target install/local
install/local/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing only the local directory..."
	/usr/bin/cmake -DCMAKE_INSTALL_LOCAL_ONLY=1 -P cmake_install.cmake
.PHONY : install/local/fast

# Special rule for the target install/strip
install/strip: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing the project stripped..."
	/usr/bin/cmake -DCMAKE_INSTALL_DO_STRIP=1 -P cmake_install.cmake
.PHONY : install/strip

# Special rule for the target install/strip
install/strip/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing the project stripped..."
	/usr/bin/cmake -DCMAKE_INSTALL_DO_STRIP=1 -P cmake_install.cmake
.PHONY : install/strip/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/giovany/Development/GioEngine/build/CMakeFiles /home/giovany/Development/GioEngine/build//CMakeFiles/progress.marks
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/giovany/Development/GioEngine/build/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named GioEngine

# Build rule for target.
GioEngine: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 GioEngine
.PHONY : GioEngine

# fast build rule for target.
GioEngine/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/GioEngine.dir/build.make CMakeFiles/GioEngine.dir/build
.PHONY : GioEngine/fast

#=============================================================================
# Target rules for targets named IMGUI

# Build rule for target.
IMGUI: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 IMGUI
.PHONY : IMGUI

# fast build rule for target.
IMGUI/fast:
	$(MAKE) $(MAKESILENT) -f libs/CMakeFiles/IMGUI.dir/build.make libs/CMakeFiles/IMGUI.dir/build
.PHONY : IMGUI/fast

#=============================================================================
# Target rules for targets named uninstall

# Build rule for target.
uninstall: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 uninstall
.PHONY : uninstall

# fast build rule for target.
uninstall/fast:
	$(MAKE) $(MAKESILENT) -f libs/glfw/CMakeFiles/uninstall.dir/build.make libs/glfw/CMakeFiles/uninstall.dir/build
.PHONY : uninstall/fast

#=============================================================================
# Target rules for targets named glfw

# Build rule for target.
glfw: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 glfw
.PHONY : glfw

# fast build rule for target.
glfw/fast:
	$(MAKE) $(MAKESILENT) -f libs/glfw/src/CMakeFiles/glfw.dir/build.make libs/glfw/src/CMakeFiles/glfw.dir/build
.PHONY : glfw/fast

#=============================================================================
# Target rules for targets named update_mappings

# Build rule for target.
update_mappings: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 update_mappings
.PHONY : update_mappings

# fast build rule for target.
update_mappings/fast:
	$(MAKE) $(MAKESILENT) -f libs/glfw/src/CMakeFiles/update_mappings.dir/build.make libs/glfw/src/CMakeFiles/update_mappings.dir/build
.PHONY : update_mappings/fast

#=============================================================================
# Target rules for targets named Core

# Build rule for target.
Core: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 Core
.PHONY : Core

# fast build rule for target.
Core/fast:
	$(MAKE) $(MAKESILENT) -f src/Editor/CMakeFiles/Core.dir/build.make src/Editor/CMakeFiles/Core.dir/build
.PHONY : Core/fast

#=============================================================================
# Target rules for targets named Highlight

# Build rule for target.
Highlight: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 Highlight
.PHONY : Highlight

# fast build rule for target.
Highlight/fast:
	$(MAKE) $(MAKESILENT) -f src/Editor/CMakeFiles/Highlight.dir/build.make src/Editor/CMakeFiles/Highlight.dir/build
.PHONY : Highlight/fast

#=============================================================================
# Target rules for targets named Configurations

# Build rule for target.
Configurations: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 Configurations
.PHONY : Configurations

# fast build rule for target.
Configurations/fast:
	$(MAKE) $(MAKESILENT) -f src/Editor/CMakeFiles/Configurations.dir/build.make src/Editor/CMakeFiles/Configurations.dir/build
.PHONY : Configurations/fast

#=============================================================================
# Target rules for targets named Canvas

# Build rule for target.
Canvas: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 Canvas
.PHONY : Canvas

# fast build rule for target.
Canvas/fast:
	$(MAKE) $(MAKESILENT) -f src/Editor/CMakeFiles/Canvas.dir/build.make src/Editor/CMakeFiles/Canvas.dir/build
.PHONY : Canvas/fast

#=============================================================================
# Target rules for targets named ProjectManager

# Build rule for target.
ProjectManager: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 ProjectManager
.PHONY : ProjectManager

# fast build rule for target.
ProjectManager/fast:
	$(MAKE) $(MAKESILENT) -f src/Core/CMakeFiles/ProjectManager.dir/build.make src/Core/CMakeFiles/ProjectManager.dir/build
.PHONY : ProjectManager/fast

src/Core/main.o: src/Core/main.cpp.o
.PHONY : src/Core/main.o

# target to build an object file
src/Core/main.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/GioEngine.dir/build.make CMakeFiles/GioEngine.dir/src/Core/main.cpp.o
.PHONY : src/Core/main.cpp.o

src/Core/main.i: src/Core/main.cpp.i
.PHONY : src/Core/main.i

# target to preprocess a source file
src/Core/main.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/GioEngine.dir/build.make CMakeFiles/GioEngine.dir/src/Core/main.cpp.i
.PHONY : src/Core/main.cpp.i

src/Core/main.s: src/Core/main.cpp.s
.PHONY : src/Core/main.s

# target to generate assembly for a file
src/Core/main.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/GioEngine.dir/build.make CMakeFiles/GioEngine.dir/src/Core/main.cpp.s
.PHONY : src/Core/main.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... install"
	@echo "... install/local"
	@echo "... install/strip"
	@echo "... list_install_components"
	@echo "... rebuild_cache"
	@echo "... uninstall"
	@echo "... update_mappings"
	@echo "... Canvas"
	@echo "... Configurations"
	@echo "... Core"
	@echo "... GioEngine"
	@echo "... Highlight"
	@echo "... IMGUI"
	@echo "... ProjectManager"
	@echo "... glfw"
	@echo "... src/Core/main.o"
	@echo "... src/Core/main.i"
	@echo "... src/Core/main.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

